server:
port: 8080

spring:
    datasource:
        platform: postgres
        url: jdbc:postgresql://ec2-23-23-162-138.compute-1.amazonaws.com:5432/d5ekirs498kff6
        username: lhiqqdnakiuitr
        password: d2cefb8dd0837c440678bda3dbbd1c207c92e4763ee7e21610d75a03f1f0f708
        driverClassName: org.postgresql.Driver
        initialization-mode: always
        initialize: true
        schema: classpath:/schema-postgresql.sql

 

    jpa: 
        hibernate:
            ddl-auto: create-drop